"""initial schema

Tables are autogenerated from the models. Hand-added: the pgvector extension
(used by the rules corpus in build step 4) and the proposal gate trigger.

Revision ID: 0001
Revises:
Create Date: 2026-09-12 13:11:08.175466
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The human gate, in the schema rather than the UI:
#   - a proposal is born pending_review (nothing the agent writes is ever pre-approved)
#   - a reviewed proposal is immutable
#   - "approved" means approved as drafted; changing the letter requires "edited"
# The reviewer-required-to-leave-pending rule is the ck_proposals_reviewer_iff_reviewed check.
PROPOSAL_GATE_FUNCTION = """
CREATE FUNCTION enforce_proposal_gate() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'pending_review' THEN
            RAISE EXCEPTION 'proposal must be created as pending_review, not %', NEW.status
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.status <> 'pending_review' THEN
        RAISE EXCEPTION 'proposal % was already reviewed (%) and is immutable', OLD.id, OLD.status
            USING ERRCODE = 'check_violation';
    END IF;

    IF NEW.status = 'approved' AND (
        NEW.letter_md IS DISTINCT FROM OLD.letter_md
        OR NEW.disposition IS DISTINCT FROM OLD.disposition
        OR NEW.items IS DISTINCT FROM OLD.items
    ) THEN
        RAISE EXCEPTION 'approved means approved as drafted; use status edited to change the proposal'
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$
"""

PROPOSAL_GATE_TRIGGER = """
CREATE TRIGGER proposals_gate
    BEFORE INSERT OR UPDATE ON proposals
    FOR EACH ROW EXECUTE FUNCTION enforce_proposal_gate();
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='received', nullable=False),
    sa.Column('submitter', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('received', 'extracting', 'reconciling', 'screening', 'agent_review', 'pending_review', 'closed')", name=op.f('ck_cases_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_domain'), 'cases', ['domain'], unique=False)
    op.create_table('circuit_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('utility', sa.String(length=64), nullable=False),
    sa.Column('feeder_id', sa.String(length=64), nullable=False),
    sa.Column('line_section_id', sa.String(length=64), nullable=False),
    sa.Column('line_section_peak_kw', sa.Numeric(), nullable=True),
    sa.Column('existing_der_kw', sa.Numeric(), nullable=True),
    sa.Column('service_transformer_kva', sa.Numeric(), nullable=True),
    sa.Column('max_fault_current_a', sa.Numeric(), nullable=True),
    sa.Column('device_interrupting_rating_a', sa.Numeric(), nullable=True),
    sa.Column('primary_line_type', sa.String(length=32), nullable=True),
    sa.Column('substation_aggregate_der_kw', sa.Numeric(), nullable=True),
    sa.Column('transmission_construction_required', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_as_of', sa.Date(), nullable=True),
    sa.Column('synthetic_fields', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("synthetic_fields <@ ARRAY['line_section_peak_kw', 'existing_der_kw', 'service_transformer_kva', 'max_fault_current_a', 'device_interrupting_rating_a', 'primary_line_type', 'substation_aggregate_der_kw', 'transmission_construction_required']::text[]", name=op.f('ck_circuit_models_synthetic_fields_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuit_models')),
    sa.UniqueConstraint('utility', 'feeder_id', 'line_section_id', name=op.f('uq_circuit_models_utility_feeder_id_line_section_id'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('step_budget', sa.Integer(), nullable=False),
    sa.Column('steps_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_ceiling_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('terminated_by', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("terminated_by IS NULL OR terminated_by IN ('proposal', 'step_budget', 'cost_ceiling', 'error')", name=op.f('ck_agent_runs_terminated_by_valid')),
    sa.CheckConstraint('(terminated_by IS NULL) = (ended_at IS NULL)', name=op.f('ck_agent_runs_termination_recorded')),
    sa.CheckConstraint('cost_ceiling_usd > 0', name=op.f('ck_agent_runs_cost_ceiling_positive')),
    sa.CheckConstraint('step_budget > 0', name=op.f('ck_agent_runs_step_budget_positive')),
    sa.CheckConstraint('steps_used >= 0 AND steps_used <= step_budget', name=op.f('ck_agent_runs_steps_within_budget')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_agent_runs_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_case_id'), 'agent_runs', ['case_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('observed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("jsonb_typeof(observed) = 'array'", name=op.f('ck_discrepancies_observed_is_array')),
    sa.CheckConstraint('material IS NULL OR rationale IS NOT NULL', name=op.f('ck_discrepancies_judgment_has_rationale')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_discrepancies_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discrepancies'))
    )
    op.create_index(op.f('ix_discrepancies_case_id'), 'discrepancies', ['case_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_documents_sha256_hex')),
    sa.CheckConstraint('page_count >= 0', name=op.f('ck_documents_page_count_nonneg')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_documents_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('case_id', 'sha256', name=op.f('uq_documents_case_id_sha256'))
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('interconnection_applications',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('utility', sa.String(length=64), nullable=False),
    sa.Column('applicant_name', sa.Text(), nullable=True),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('circuit_model_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_interconnection_applications_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['circuit_model_id'], ['circuit_models.id'], name=op.f('fk_interconnection_applications_circuit_model_id_circuit_models')),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_interconnection_applications'))
    )
    op.create_table('rule_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('rule_set', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('computed', sa.Numeric(), nullable=True),
    sa.Column('threshold', sa.Numeric(), nullable=True),
    sa.Column('citation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('missing_inputs', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('synthetic_inputs', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("input_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_rule_results_input_hash_hex')),
    sa.CheckConstraint("status <> 'FAIL' OR classification IS NOT NULL", name=op.f('ck_rule_results_fail_classified')),
    sa.CheckConstraint("status <> 'INCONCLUSIVE' OR reason IS NOT NULL", name=op.f('ck_rule_results_inconclusive_has_reason')),
    sa.CheckConstraint("status = 'INCONCLUSIVE' OR citation IS NOT NULL", name=op.f('ck_rule_results_decided_result_cited')),
    sa.CheckConstraint("status IN ('PASS', 'FAIL', 'INCONCLUSIVE')", name=op.f('ck_rule_results_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_rule_results_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_results'))
    )
    op.create_index(op.f('ix_rule_results_case_id'), 'rule_results', ['case_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role <> 'tool' OR tool IS NOT NULL", name=op.f('ck_agent_steps_tool_step_names_tool')),
    sa.CheckConstraint("role IN ('assistant', 'tool')", name=op.f('ck_agent_steps_role_valid')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps')),
    sa.UniqueConstraint('run_id', 'n', name=op.f('uq_agent_steps_run_id_n'))
    )
    op.create_table('pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('page_no >= 1', name=op.f('ck_pages_page_no_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('document_id', 'page_no', name=op.f('uq_pages_document_id_page_no'))
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('model_disposition', sa.String(length=32), nullable=True),
    sa.Column('letter_md', sa.Text(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('guardrail_verdicts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending_review', nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending_review') = (reviewed_by IS NULL AND reviewed_at IS NULL)", name=op.f('ck_proposals_reviewer_iff_reviewed')),
    sa.CheckConstraint("jsonb_typeof(guardrail_verdicts) = 'array'", name=op.f('ck_proposals_guardrail_verdicts_is_array')),
    sa.CheckConstraint("jsonb_typeof(items) = 'array'", name=op.f('ck_proposals_items_is_array')),
    sa.CheckConstraint('reviewed_by IS NULL OR length(btrim(reviewed_by)) > 0', name=op.f('ck_proposals_reviewer_named')),
    sa.CheckConstraint("status IN ('pending_review', 'approved', 'edited', 'rejected')", name=op.f('ck_proposals_status_valid')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_proposals_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_proposals_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    op.create_index(op.f('ix_proposals_case_id'), 'proposals', ['case_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_extracted_facts_confidence_unit')),
    sa.CheckConstraint('length(btrim(quote)) > 0', name=op.f('ck_extracted_facts_quote_nonempty')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_extracted_facts_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id', 'page_no'], ['pages.document_id', 'pages.page_no'], name=op.f('fk_extracted_facts_document_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_facts'))
    )
    op.create_index(op.f('ix_extracted_facts_case_id'), 'extracted_facts', ['case_id'], unique=False)

    op.execute(PROPOSAL_GATE_FUNCTION)
    op.execute(PROPOSAL_GATE_TRIGGER)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS proposals_gate ON proposals")
    op.execute("DROP FUNCTION IF EXISTS enforce_proposal_gate()")
    op.drop_index(op.f('ix_extracted_facts_case_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_proposals_case_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('pages')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_rule_results_case_id'), table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_table('interconnection_applications')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_discrepancies_case_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_agent_runs_case_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('circuit_models')
    op.drop_index(op.f('ix_cases_domain'), table_name='cases')
    op.drop_table('cases')
